# Generated by Django 4.1.1 on 2022-10-02 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommend_MF',
            fields=[
                ('user_no', models.OneToOneField(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('similar', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'recommend_mf',
            },
        ),
    ]
