# Generated by Django 4.1.1 on 2022-10-02 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alcohol',
            fields=[
                ('alcohol_no', models.AutoField(primary_key=True, serialize=False)),
                ('alcohol_name', models.CharField(max_length=50)),
                ('abv', models.FloatField()),
                ('material', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('brewery', models.CharField(max_length=100, null=True)),
                ('award', models.CharField(max_length=500, null=True)),
                ('like_count', models.IntegerField(null=True)),
                ('food', models.CharField(max_length=500, null=True)),
                ('tag', models.CharField(max_length=50, null=True)),
                ('size', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'alcohol',
            },
        ),
        migrations.CreateModel(
            name='Alcohol_code',
            fields=[
                ('alcohol_code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('alcohol_type', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'alcohol_code',
            },
        ),
        migrations.CreateModel(
            name='Region_code',
            fields=[
                ('region_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'region_code',
            },
        ),
        migrations.CreateModel(
            name='Alcohol_recommend',
            fields=[
                ('alcohol_no', models.OneToOneField(db_column='alcohol_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='alcohol.alcohol')),
                ('sweet', models.IntegerField()),
                ('sour', models.IntegerField()),
                ('scent', models.IntegerField()),
                ('body', models.IntegerField()),
                ('abv_level', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'alcohol_recommend',
            },
        ),
        migrations.CreateModel(
            name='Alcohol_score4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('alcohol_no', models.OneToOneField(db_column='alcohol_no', on_delete=django.db.models.deletion.CASCADE, to='alcohol.alcohol')),
            ],
            options={
                'db_table': 'alcohol_score4',
            },
        ),
        migrations.CreateModel(
            name='Alcohol_score3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('alcohol_no', models.OneToOneField(db_column='alcohol_no', on_delete=django.db.models.deletion.CASCADE, to='alcohol.alcohol')),
            ],
            options={
                'db_table': 'alcohol_score3',
            },
        ),
        migrations.CreateModel(
            name='Alcohol_score2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('alcohol_no', models.OneToOneField(db_column='alcohol_no', on_delete=django.db.models.deletion.CASCADE, to='alcohol.alcohol')),
            ],
            options={
                'db_table': 'alcohol_score2',
            },
        ),
        migrations.CreateModel(
            name='Alcohol_score1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('count', models.IntegerField(default=0)),
                ('alcohol_no', models.OneToOneField(db_column='alcohol_no', on_delete=django.db.models.deletion.CASCADE, to='alcohol.alcohol')),
            ],
            options={
                'db_table': 'alcohol_score1',
            },
        ),
        migrations.AddField(
            model_name='alcohol',
            name='alcohol_code',
            field=models.ForeignKey(db_column='alcohol_code', default='A1', on_delete=django.db.models.deletion.CASCADE, to='alcohol.alcohol_code'),
        ),
        migrations.AddField(
            model_name='alcohol',
            name='region_code',
            field=models.ForeignKey(db_column='region_code', on_delete=django.db.models.deletion.CASCADE, to='alcohol.region_code'),
        ),
    ]
