# Generated by Django 4.1.1 on 2022-10-02 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alcohol_recommend',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alcohol_recommend',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
