# Generated by Django 4.1.1 on 2022-10-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alcohol', '0002_alter_alcohol_like_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alcohol_recommend',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alcohol_recommend',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
