const testinput = [
  {
    id: "1",
    name: "1000억 유산균 막걸리",
    type: "탁주",
    reg_ingredients: "쌀",
    ingredients: "쌀, 누룩",
    alcohol: "5",
    size: "750",
    prize: "2021 대한민국 주류대상 우리술 탁주 생막걸리 부문 3년 연속 대상",
    etc: "",
    tags: "저도수",
    desc: "1000억 유산균 막걸리는 국순당이 최초로 선보인 유산균 강화 막걸리다. 식물성 유산균이 막걸리 한 병(750mL)에 1000억 마리 이상이 들어 있다. 시중에 판매되는 일반 생막걸리 한 병(자사 생막걸리 750mL 기준)당 1억 마리 가량의 유산균이 들어 있는 것과 비교하면 약 1000배 많이 들어있고, 일반 유산균음료 보다 약 100배 많이 들어 있다.",
    food: "전, 회무침",
    brewery: "국순당",
    brewery_address: "강원도 횡성군 둔내면 현천리 120",
    brewery_page: "http://www.ksdb.co.kr",
    sweet: "3",
    sour: "5",
    scent: "1",
    body: "3",
    img_link:
      "https://thesool.com/common/imageView.do?targetId=PR00000170&targetNm=PRODUCT",
  },
  {
    id: "2",
    name: "1932 새싹땅콩 햅쌀/흑미",
    type: "탁주",
    reg_ingredients: "새싹땅콩",
    ingredients: "새싹땅콩, 쌀, 흑미",
    alcohol: "6",
    size: "500, 900",
    prize: "",
    etc: "",
    tags: "",
    desc: "당해연도 고시히카리쌀과 진도산 흑미를 주 원료로 사용하였다. 새싹땅콩의 항산화 물질인 ‘레즈베라트롤’이다량 함유 되었있고, 전통누룩에서 뽑아낸 우수한 균주를 사용하였다. 합성감미료는 사용하지 않았으며, 미생물 발효 조절방식으로 냉장보관 시 신선한 맛과 주질을 유지할 수 있다. 고급한정식당, 호텔, 백화점 위주로 납품되어지고 있다.",
    food: "마늘새우",
    brewery: "(주)1932 포천일동막걸리",
    brewery_address: "경기도 포천시 일동면 운악청계로 1597",
    brewery_page:
      "https://shopping.naver.com/fresh/traditionalalcohol/stores/100159599",
    sweet: "4",
    sour: "2",
    scent: "2",
    body: "1",
    img_link:
      "https://thesool.com/common/imageView.do?targetId=PR00000210&targetNm=PRODUCT",
  },
  {
    id: "3",
    name: "2017년 햅쌀로 빚은 첫술",
    type: "탁주",
    reg_ingredients: "햅쌀",
    ingredients: "햅쌀",
    alcohol: "7",
    size: "750",
    prize: "",
    etc: "",
    tags: "탄산",
    desc: "2017년 햅쌀로 빚은 첫술은 매년 가을철, 그 해 수확한 햅쌀로 빚은 프리미엄 생 막걸리로 계절 한정 상품으로 선보인다. 올해 수확한 경북 안동 햅쌀을 원료로 빚어, 생 막걸리 특유의 탄산감이 살아있으면서도 부드럽고 신선한 쌀의 향과 맛을 느낄 수 있다.",
    food: "",
    brewery: "국순당",
    brewery_address: "강원도 횡성군 둔내면 현천리 120",
    brewery_page: "http://www.ksdb.co.kr",
    sweet: "4",
    sour: "2",
    scent: "1",
    body: "4",
    img_link:
      "https://thesool.com/common/imageView.do?targetId=PR00000211&targetNm=PRODUCT",
  },
  {
    id: "4",
    name: "52C",
    type: "증류주",
    reg_ingredients: "오이",
    ingredients: "정제수, 주정, 증류원액, 오이",
    alcohol: "17.5",
    size: "500",
    prize: "",
    etc: "",
    tags: "탄산",
    desc: "오이처럼 cool 하게 즐기는 싱싱한 오이 증류주. 예전에 유행했던 소주에 오이를 넣어 마시는 오이소주를 떠올리며 만든 술이다. 오이를 소주에 담그면 오이의 색과 향이 소주의 알코올 성분에 침출되어 소주 특유의 쓴 맛과 아로올 취를 부드럽게 하여 술 맛을 순하게 하고 이뇨작용을 활발하게 해주어 체내의 노폐물 배설을 도와주기도 한다고 한다. 오이는 차가운 성질이라 여름에 술 마실 때 나타나는 체온 상승을 어느 정도 억제해주고, 오이의 다양한 비타민은 숙취 해소에 효과가 있다고 한다. 이런 오이의 장점을 침출해 만든 세계 최초의 증류주가 52C이다. 52C를 마시면 입안 가득 오이와 멜론 향이 퍼진다.",
    food: "곱창구이",
    brewery: "청산녹수",
    brewery_address: "전라남도 장성군 장섭읍 남양촌길 19",
    brewery_page: "http://www.bluegreenkorea.co.kr",
    sweet: "3",
    sour: "2",
    scent: "5",
    body: "3",
    img_link:
      "https://thesool.com/common/imageView.do?targetId=PR00000737&targetNm=PRODUCT",
  },
  {
    id: "5",
    name: "DOK막걸리",
    type: "탁주",
    reg_ingredients: "쌀",
    ingredients: "정제수, 멥쌀, 찹쌀, 누룩, 효소, 효모",
    alcohol: "6",
    size: "1000",
    prize: "",
    etc: "",
    tags: "홈술|무감미료|혼술",
    desc: "DOK막걸리는 우리 누룩 특유의 발효 특성을 연구하여 출시한 막걸리로 막걸리 본연의 맛을 낼 수 있도록 노력한 결과입니다. 잘 익은 참외와 멜론의 달콤하고 상큼한 과육향을 싱그럽고 경쾌하게 즐길 수 있는 프리미엄 막걸리입니다.",
    food: "",
    brewery: "독브루어리",
    brewery_address: "경기 김포시 하성면 누산봉성로237번길 163",
    brewery_page: "https://www.instagram.com/dokbrewery/?hl=ko",
    sweet: "4",
    sour: "2",
    scent: "2",
    body: "2",
    img_link:
      "https://thesool.com/common/imageView.do?targetId=PR00000669&targetNm=PRODUCT",
  },
  {
    id: "6",
    name: "골디락스",
    type: "탁주",
    reg_ingredients: "쌀",
    ingredients: "정제수, 멥쌀, 찹쌀, 누룩, 종국, 효모, 밀",
    alcohol: "12",
    size: "500",
    prize: "",
    etc: "",
    tags: "무감미료",
    desc: "싱그러운 과일향과 부드러운 목 넘김으로 마시기 딱 좋은 막걸리. Ice 공법으로 차갑게 발효하고 더 차갑게 숙성했다. 담백한 맛의 멥쌀과 감칠맛 나는 찹쌀을 오랜 연구개발 끝에 최적의 비율로 사용하여 소박한 단맛을 구현하였고, 여기에 12℃ 저온에서 30일간의 발효와 12℃에서 30일간의 숙성 과정을 거친 깔끔한 막걸리이다. 제품명 G12에서 12는 알코올 도수 12도를 의미하고, G는 마시기 딱 좋은 조화로운 맛의 균형이라는 제품 특성을 담을 수 있도록 Goldilocks의 첫 글자를 따서 이름을 지었다. Goldilocks는 영국의 전래동화 '골디락스와 세 마리 곰' 주인공 소녀의 이름에서 유래한 용어로 뜨겁지도 차갑지도 않은 적당한 상태를 의미한다.",
    food: "닭백숙, 오리백숙, 편육, 새우젓, 겉절이",
    brewery: "청산녹수",
    brewery_address: "전라남도 장성군 장섭읍 남양촌길 19",
    brewery_page: "http://www.bluegreenkorea.co.kr",
    sweet: "5",
    sour: "1",
    scent: "1",
    body: "4",
    img_link:
      "https://thesool.com/common/imageView.do?targetId=PR00000707&targetNm=PRODUCT",
  },
  {
    id: "7",
    name: "SSOA-포도",
    type: "리큐르/기타주류",
    reg_ingredients: "포도",
    ingredients: "포도",
    alcohol: "5",
    size: "355",
    prize: "2014 대한민국우리술품평회 대상 (기타주류 부문)",
    etc: "",
    tags: "탄산|저도수|혼술",
    desc: "포도주를 이용한 특유한 스파클링와인으로서 우수한 포천포도를 와인으로 제조하여 뛰어난 맛과 향을 느낄 수 있으며 탄산의 시원함을 동시에 느낄 수 있고 목넘김이 아주 좋은 것이 특징이다.",
    food: "피자, 치킨",
    brewery: "㈜포천조술당",
    brewery_address: "경기 포천시 화현면 화동로 432번길 12",
    brewery_page: "",
    sweet: "2",
    sour: "2",
    scent: "4",
    body: "3",
    img_link:
      "https://thesool.com/common/imageView.do?targetId=PR00000644&targetNm=PRODUCT",
  },
  {
    id: "8",
    name: "The 찾을수록",
    type: "증류주",
    reg_ingredients: "사과와인",
    ingredients:
      "사과와인, 정제수, 주정, 농축액 (복숭아, 포도, 사과, 감귤, 생강, 커피 향 등)",
    alcohol: "15",
    size: "360",
    prize: "",
    etc: "2016 찾아가는 양조장",
    tags: "",
    desc: "더찾을수록 시리즈는 한국애플리즈는 7년의 부단한 연구개발 끝에 2013년 사과와인을 베이스로한 사과소주 6종을 출시하였다. 복숭아, 청포도, 사과, 감귤, 생강, 아메리카노를 가미하여 탄생한 6종의 사과소주다. 패키지 디자인은 녹색 희석식 소주와 흡사하지만 제품은 증류주가 아닌 과실주로 분류된다. 미국 마켓의 경우 맥주와 와인 판매허가만 있는 경우 소주를 판매할 수 없는 점에 착안하여 디자인은 소주이나 제품은 사과와인으로 미국 내 많은 마켓에 입점하기 위한 전략에서 디자인된 제품이다.",
    food: "스낵",
    brewery: "㈜한국애플리즈",
    brewery_address: "경북 의성군 단촌면 일직점곡로 755",
    brewery_page: "http://www.applewine.co.kr/",
    sweet: "1",
    sour: "1",
    scent: "1",
    body: "5",
    img_link:
      "https://thesool.com/common/imageView.do?targetId=PR00000554&targetNm=PRODUCT",
  },
  {
    id: "9",
    name: "가야 프리미엄 막걸리",
    type: "탁주",
    reg_ingredients: "쌀",
    ingredients: "쌀",
    alcohol: "6",
    size: "750",
    prize: "",
    etc: "",
    tags: "",
    desc: "풍부한 일조량은 받고 자란 김해 쌀로 만든 가야는 감미료를 전혀 넣지 않았음에도 꽃 향기 등이 나고 새콤달콤한 맛을 느낄 수 있습니다.",
    food: "",
    brewery: "가야양조장",
    brewery_address: "경남 김해시 한림면 한림로 46번길 79-1",
    brewery_page: "https://www.instagram.com/gaya_brewery/?hl=ko",
    sweet: "3",
    sour: "2",
    scent: "2",
    body: "4",
    img_link:
      "https://thesool.com/common/imageView.do?targetId=PR00000056&targetNm=PRODUCT",
  },
  {
    id: "10",
    name: "가야곡왕주",
    type: "약주, 청주",
    reg_ingredients: "국화",
    ingredients: "쌀, 국화, 구기자, 오미자, 솔잎, 매실",
    alcohol: "13",
    size: "750",
    prize: "",
    etc: "전통식품명인 제13호 남상란",
    tags: "명절",
    desc: "조선의 마지막국모 명성황후 민씨의 친정에서 빚던 가양주로 종묘대제의 제주(祭酒)로 사용되고 있다. 제철에 채취한 초, 근, 목, 피를 이용해야 약재의 효능을 최고로 끌어올릴 수 있는데, 가야곡왕주는 가야곡의 맑은 물과 제철솔잎, 구절초, 홍삼, 매실 등을 이용해 술에 다양한 맛과 향을 불어 넣은 좋은 약주라 할 수 있다.",
    food: "소고기나 돼지고기를 양념한 갈비",
    brewery: "민속주왕주",
    brewery_address: "충남 논산시 원댕이길 2-65",
    brewery_page: "",
    sweet: "2",
    sour: "2",
    scent: "3",
    body: "2",
    img_link:
      "https://thesool.com/common/imageView.do?targetId=PR00000350&targetNm=PRODUCT",
  },
];

export default testinput;