# Generated by Django 4.1.1 on 2022-10-02 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=13, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=20)),
                ('gender', models.IntegerField(default=0)),
                ('birth', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='User_kind_code',
            fields=[
                ('kind_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('kind_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'user_kind_code',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('user_no', models.OneToOneField(db_column='user_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('reply_list', models.JSONField()),
            ],
            options={
                'db_table': 'survey',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_kind',
            field=models.ForeignKey(db_column='user_kind', null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user_kind_code'),
        ),
    ]
