# Generated by Django 4.1.1 on 2022-10-02 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alcohol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('alcohol_no', models.OneToOneField(db_column='alcohol_no', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='alcohol.alcohol')),
                ('ranking', models.IntegerField()),
            ],
            options={
                'db_table': 'ranking',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_no', models.IntegerField(default=0)),
                ('alcohol_no', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('comment', models.CharField(default='', max_length=150)),
                ('sweet', models.IntegerField(default=0)),
                ('sour', models.IntegerField(default=0)),
                ('scent', models.IntegerField(default=0)),
                ('body', models.IntegerField(default=0)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'review',
            },
        ),
    ]
